<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mybot">

  <xacro:include filename="$(find my_robot)/urdf/mybot.plugins.xacro" />

  <xacro:property name="base_width" value="0.0"/>
  <xacro:property name="base_len" value="0.0"/>
  <xacro:property name="wheel_radius" value="0.0"/>
  <xacro:property name="base_wheel_gap" value="0.0"/>
  <xacro:property name="wheel_separation" value="0.0"/>
  <xacro:property name="wheel_joint_offset" value="0.0"/>

  <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>
  <xacro:property name="caster_wheel_mass" value="0.001"/>
  <xacro:property name="caster_wheel_joint_offset" value="-0.052"/>

  <xacro:property name="camera_size" value="0.02"/>
  <xacro:property name="camera_origin_x" value="0.2"/>
  <xacro:property name="camera_origin_y" value="0.2"/>
  <xacro:property name="camera_origin_z" value="3.0"/>

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial> 
  </xacro:macro>

  <xacro:macro name="default_pose" params="pose">
  <pose value="-2 -2 2 0 0 0"/>
  </xacro:macro>


  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.1 0.1 0.01"/>
      </geometry>
    </collision>
    <static>1</static>
    <xacro:default_inertial mass="200"/>
  </link>

  <!--Camera-->
  <link name="camera">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.001 0.001 0.005"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.02"/>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="-3 1.5 1.5" rpy="1.570796 1.570796 0"/>
    <parent link="base_link"/>
    <child link="camera"/>
  </joint>

</robot>